# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Bathysseur
                                 A QGIS plugin
 Ce plugin permet d'interpoler la bathymétrie d'un fleuve ou d'une rivière entre deux profils bathymétriques.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-02-20
        copyright            : (C) 2023 by Florent Bourhis (Cerema)
        email                : florent.bourhis@cerema.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Bathysseur class from file Bathysseur.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Bathysseur import Bathysseur
    return Bathysseur(iface)
